<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>resourcemonitor</AssemblyName>
    <RootNamespace>Calloatti.ResourceMonitor</RootNamespace>
    <TimberbornPath>C:\Program Files (x86)\Steam\steamapps\common\timberborn_main\Timberborn_Data\Managed</TimberbornPath>
  </PropertyGroup>

  <Import Project="CommonModSettings.props" />

  <ItemGroup>
    <DoNotPublicize Include="Timberborn.GameDistricts:Timberborn.GameDistricts.DistrictBuilding.ReassignedDistrict" />
    <DoNotPublicize Include="Timberborn.GameDistricts:Timberborn.GameDistricts.DistrictBuilding.ReassignedInstantDistrict" />
    <DoNotPublicize Include="Timberborn.GameDistricts:Timberborn.GameDistricts.DistrictBuilding.ReassignedConstructionDistrict" />
    <DoNotPublicize Include="Timberborn.CoreUI:Timberborn.CoreUI.RadioToggle.RadioButtonSelected" />
    <DoNotPublicize Include="Timberborn.BlueprintSystem:Timberborn.BlueprintSystem.ComponentSpec.EqualityContract" />
    <DoNotPublicize Include="Timberborn.BlueprintSystem:Timberborn.BlueprintSystem.ComponentSpec.PrintMembers" />
  </ItemGroup>

</Project>

